name: d2iq-release-tag-version

on:
  workflow_dispatch:
    inputs:
      releaseTag:
        description: 'Existing Tag to checkout.'
        type: string
        required: true
        default: ''
      imageName:
        description: 'Release Image Name'
        type: string
        required: true
        default: 'ghcr.io/mesosphere/gitea:latest'

jobs:
  docker-rootless:
    runs-on: 
      - self-hosted
      - large
    permissions:
        contents: read
        packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.releaseTag }}
          fetch-tags: true
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build rootless docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          file: Dockerfile.rootless
          tags: ${{ inputs.imageName }}
